<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/cfa_subscription_sync.php';
final class Phase5Store implements CfaSubscriptionStore {
 public array $rows=[],$events=[],$checkouts=[]; public function lock():void{} public function unlock():void{} public function begin():void{} public function commit():void{} public function rollback():void{}
 public function seen(string $e):bool{return isset($this->events[$e]);} public function mark(string $e,string $t):void{$this->events[$e]=$t;} public function subscriber(int $i):?array{return $this->rows[$i]??null;}
 public function bySubscription(string $id):?array{foreach($this->rows as $r)if(($r['stripe_subscription_id']??'')===$id)return$r;return null;} public function byCustomer(string $id):?array{$f=null;foreach($this->rows as $r)if(($r['stripe_customer_id']??'')===$id){if($f)throw new RuntimeException('Ambiguous Stripe identity');$f=$r;}return$f;}
 public function checkout(string $id):?array{return $this->checkouts[$id]??null;} public function save(array $r):void{$this->rows[(int)$r['id']]=$r;}
 public function query(string $s,array $a=[]):array{return[];}
}
function ok(bool $v,string $m):void{if(!$v)throw new RuntimeException($m);} function ev(string $id,string $type,int $t,array $o):array{return['id'=>$id,'type'=>$type,'created'=>$t,'data'=>['object'=>$o]];}
function sub(string $status='active',int $created=100,int $period=200,bool $cancel=false):array{return['id'=>'sub_1','customer'=>'cus_1','created'=>$created,'status'=>$status,'current_period_end'=>$period,'cancel_at_period_end'=>$cancel,'items'=>['data'=>[['price'=>['id'=>'price_month']]]]];}
$s=new Phase5Store();$s->rows[1]=['id'=>1,'email'=>'a@example.test','plan'=>'free','status'=>'inactive','stripe_customer_id'=>'cus_1','stripe_subscription_id'=>null,'stripe_subscription_status'=>''];$s->checkouts['cs_1']=['subscriber_id'=>1,'stripe_customer_id'=>'cus_1'];$cur=sub();$get=function(string $id)use(&$cur):array{return$cur;};$p=['price_month'=>'monthly'];
$o=['id'=>'cs_1','customer'=>'cus_1','subscription'=>'sub_1','mode'=>'subscription'];ok(cfa_process_subscription_event($s,ev('evt_1','checkout.session.completed',100,$o),$get,$p,150)==='processed','new');ok(cfa_process_subscription_event($s,ev('evt_1','checkout.session.completed',100,$o),$get,$p,150)==='duplicate','duplicate');
$cur=sub('past_due',100,200);ok(cfa_process_subscription_event($s,ev('evt_2','invoice.payment_failed',110,['subscription'=>'sub_1']),$get,$p,150)==='processed','failure');$cur=sub('active',100,300);ok(cfa_process_subscription_event($s,ev('evt_3','invoice.paid',120,['subscription'=>'sub_1']),$get,$p,150)==='processed','recovery');
$cur=sub('active',100,250,true);ok(cfa_process_subscription_event($s,ev('evt_4','customer.subscription.updated',130,$cur),$get,$p,150)==='processed','schedule');ok((int)$s->rows[1]['cancel_at_period_end']===1,'flag');$cur=sub('active',100,250);ok(cfa_process_subscription_event($s,ev('evt_5','customer.subscription.updated',140,$cur),$get,$p,150)==='processed','reverse');$cur=sub('canceled',100,250);$cur['ended_at']=200;ok(cfa_process_subscription_event($s,ev('evt_6','customer.subscription.deleted',150,$cur),$get,$p,150)==='processed','cancel');$cur=sub('active',100,500);ok(cfa_process_subscription_event($s,ev('evt_old','customer.subscription.updated',90,$cur),$get,$p,150)==='stale','stale terminal state');
$e=cfa_evaluate_advisor_entitlement(array_merge($s->rows[1],['stripe_subscription_status'=>'past_due','past_due_started_at'=>'2025-01-01 00:00:00']),new DateTimeImmutable('2025-01-03T00:00:00Z'));ok($e['has_premium']&&$e['portal_available'],'portal');ok(cfa_billing_customer(['id'=>1,'stripe_customer_id'=>'cus_1'],1)==='cus_1'&&cfa_billing_customer(['id'=>2,'stripe_customer_id'=>'cus_1'],1)===null,'isolation');$register=file_get_contents(__DIR__.'/../calcforadvisors/register-free.php');ok(str_contains($register,'LOWER(TRIM(email)) = LOWER(TRIM(?))'),'case-insensitive duplicate signup');echo"Phase 5 subscription lifecycle tests passed (16 checks).\n";
