<?php
/** Shared disclosure for exported reports; financial inputs remain per calculator. */
function rb_report_context(TCPDF $pdf): void
{
    $pdf->AddPage();
    $pdf->SetTextColor(30, 41, 59);
    $pdf->SetFont('helvetica', 'B', 13);
    $pdf->MultiCell(0, 8, 'Report context and assumptions', 0, 'L');
    $pdf->SetFont('helvetica', '', 10);
    $pdf->MultiCell(0, 6, 'Prepared ' . gmdate('Y-m-d H:i') . ' UTC. Generated by RonBelisle.com.', 0, 'L');
    $pdf->Ln(3);
    $pdf->MultiCell(0, 6, 'This report reflects the inputs and results supplied from the calculator at export time. It is an educational illustration, not an independently verified valuation, personalized recommendation, or guarantee. Review the input amounts, ages, dates, return and inflation assumptions, payment timing, fees, taxes, and supported statutory scope shown in the report and calculator before relying on it. Assumptions not shown must not be presumed included.', 0, 'L');
    $pdf->Ln(3);
    $pdf->MultiCell(0, 6, 'Retain the scenario inputs with this report, identify the alternatives compared, and confirm any statutory limitations with an appropriate professional. AI explanations, where available, are separate from the numerical model and require review.', 0, 'L');
}
