<?php
error_reporting(0);
ini_set('display_errors', 0);
ob_start();
require_once $_SERVER['DOCUMENT_ROOT'] . '/includes/session_bootstrap.php';
rb_session_start();
require_once __DIR__ . '/../includes/db_config.php';
require_once __DIR__ . '/../vendor/autoload.php';

require_once __DIR__ . '/../includes/has_premium_access.php';
if (!has_premium_access()) {
    header('Content-Type: application/json');
    http_response_code(403);
    die(json_encode(['error' => 'Premium subscription required']));
}

$data = json_decode(file_get_contents('php://input'), true);
if (!$data) {
    header('Content-Type: application/json');
    http_response_code(400);
    die(json_encode(['error' => 'Missing data']));
}

$fra = $data['fra'] ?? ['years' => 67, 'months' => 0];
$fraStr = $fra['years'] . ($fra['months'] > 0 ? ' and ' . $fra['months'] . ' months' : '');
$planStop = $data['plannedRetirementAge'] ?? '—';
$actualStop = $data['actualStopAge'] ?? '—';
$claimAge = $data['claimingAge'] ?? '—';
$deltaMo = (float) ($data['deltaMo'] ?? 0);
$deltaLife = (float) ($data['deltaLife'] ?? 0);
$nestEgg = (float) ($data['nestEgg'] ?? 0);
$planMonthly = (float) ($data['planMonthly'] ?? 0);
$actualMonthly = (float) ($data['actualMonthly'] ?? 0);
$life = (int) ($data['lifeExpectancy'] ?? 85);
$wdr = $data['withdrawalRatePct'] ?? 4;

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->SetMargins(18, 18, 18);
$pdf->SetAutoPageBreak(true, 15);
$pdf->AddPage();

$pdf->SetFillColor(37, 99, 235);
$pdf->Rect(0, 0, 210, 40, 'F');
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetY(12);
$pdf->Cell(0, 10, 'Early Exit Impact Summary', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 11);
$pdf->SetY(28);
$pdf->Cell(0, 6, 'One-Page Decision Guide', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetY(50);

$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(37, 99, 235);
$pdf->Cell(0, 8, 'Your Timeline', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 11);
$pdf->MultiCell(0, 6, 'FRA: ' . $fraStr . '  ·  Planned stop: ' . $planStop . '  ·  Actual stop: ' . $actualStop . '  ·  Claim at: ' . $claimAge, 0, 'L');
$pdf->Ln(4);

$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(37, 99, 235);
$pdf->Cell(0, 8, 'Estimated Impact of Stopping Early', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 11);
$pdf->SetFillColor(254, 242, 242);
$pdf->Cell(0, 8, 'Monthly reduction: $' . number_format(abs($deltaMo), 0) . '/mo', 0, 1, 'L', true);
$pdf->SetFillColor(255, 251, 235);
$pdf->Cell(0, 8, 'Lifetime hit to age ' . $life . ': $' . number_format(abs($deltaLife), 0), 0, 1, 'L', true);
$pdf->SetFillColor(240, 253, 244);
$pdf->Cell(0, 8, 'Extra nest egg needed @ ' . $wdr . '%: $' . number_format($nestEgg, 0), 0, 1, 'L', true);
$pdf->Ln(6);

$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(37, 99, 235);
$pdf->Cell(0, 8, 'Benefit at Claiming Age ' . $claimAge, 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 11);
$pdf->SetFillColor(239, 246, 255);
$pdf->Cell(0, 8, 'Work as planned (stop ' . $planStop . '): $' . number_format($planMonthly, 0) . '/mo', 0, 1, 'L', true);
$pdf->SetFillColor(254, 242, 242);
$pdf->Cell(0, 8, 'Stop at ' . $actualStop . ': $' . number_format($actualMonthly, 0) . '/mo', 0, 1, 'L', true);
$pdf->Ln(8);

$pdf->SetFont('helvetica', 'B', 12);
$pdf->SetTextColor(37, 99, 235);
$pdf->Cell(0, 7, 'Takeaway', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 10);
if ($deltaMo > 5) {
    $msg = 'Stopping at ' . $actualStop . ' instead of ' . $planStop . ' may reduce your estimated benefit by about $'
        . number_format(abs($deltaMo), 0) . '/month. Replacing that cut at a ' . $wdr
        . '% withdrawal rate would require roughly $' . number_format($nestEgg, 0) . ' more in savings.';
} else {
    $msg = 'Under these assumptions, stopping earlier does not show a large change in the estimated benefit. Confirm with your SSA statement and my Social Security account.';
}
$pdf->MultiCell(0, 5, $msg, 0, 'L');
$pdf->Ln(8);

$pdf->SetFont('helvetica', 'I', 8);
$pdf->SetTextColor(120, 120, 120);
$pdf->MultiCell(0, 4, 'Educational estimate only — not an official SSA projection. Generated by RonBelisle.com on ' . date('F j, Y') . '.', 0, 'L');

$pdfBytes = $pdf->Output('', 'S');
ob_end_clean();
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="SS_Early_Exit_Summary_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . strlen($pdfBytes));
header('Cache-Control: private, max-age=0, must-revalidate');
echo $pdfBytes;
exit;
