<?php
error_reporting(0);
ini_set('display_errors', 0);
ob_start();
session_start();
require_once '../includes/db_config.php';
require_once '../vendor/autoload.php';

if (!isset($_SESSION['user_id'])) {
    header('Content-Type: application/json');
    http_response_code(401);
    die(json_encode(['error' => 'Not logged in']));
}

$user_id = $_SESSION['user_id'];
$stmt = $conn->prepare("SELECT subscription_status FROM users WHERE id = ?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$user = $result->fetch_assoc();
if ($user['subscription_status'] !== 'premium') {
    header('Content-Type: application/json');
    http_response_code(403);
    die(json_encode(['error' => 'Premium subscription required']));
}

$data = json_decode(file_get_contents('php://input'), true);
if (!$data) {
    header('Content-Type: application/json');
    http_response_code(400);
    die(json_encode(['error' => 'Missing data']));
}

$fra = $data['fra'] ?? ['years' => 67, 'months' => 0];
$fraStr = $fra['years'] . ($fra['months'] > 0 ? ' and ' . $fra['months'] . ' months' : '');
$a = $data['claimAgeA'] ?? 62;
$b = $data['claimAgeB'] ?? 67;
$c = $data['claimAgeC'] ?? 70;
$life = $data['lifeExpectancy'] ?? 85;
$best = $data['bestScenario'] ?? [];
$bestAge = $best['age'] ?? $b;

$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);
$pdf->SetMargins(18, 18, 18);
$pdf->SetAutoPageBreak(TRUE, 15);
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 10);

// Header
$pdf->SetFillColor(59, 130, 246);
$pdf->Rect(0, 0, 210, 40, 'F');
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 22);
$pdf->SetY(12);
$pdf->Cell(0, 10, 'Your Social Security Claiming Summary', 0, 1, 'C');
$pdf->SetFont('helvetica', '', 11);
$pdf->SetY(28);
$pdf->Cell(0, 6, 'One-Page Decision Guide', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);
$pdf->SetY(50);

// Section 1: Your FRA & PIA
$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(59, 130, 246);
$pdf->Cell(0, 8, 'Your Full Retirement Age', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 11);
$pdf->Cell(0, 6, 'FRA: ' . $fraStr . ' — Your benefit at FRA: $' . number_format($data['monthlyPIA'] ?? 0, 0) . '/month', 0, 1);
$pdf->Ln(6);

// Section 2: Monthly benefits at each claiming age
$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(59, 130, 246);
$pdf->Cell(0, 8, 'Monthly Benefit by Claiming Age', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 11);
$pdf->SetFillColor(240, 249, 255);
$pdf->Cell(0, 7, 'Claim at ' . $a . ': $' . number_format($data['monthlyA'] ?? 0, 0) . '/mo', 0, 1, 'L', true);
$pdf->Cell(0, 7, 'Claim at ' . $b . ': $' . number_format($data['monthlyB'] ?? 0, 0) . '/mo', 0, 1, 'L', true);
$pdf->Cell(0, 7, 'Claim at ' . $c . ': $' . number_format($data['monthlyC'] ?? 0, 0) . '/mo', 0, 1, 'L', true);
$pdf->Ln(6);

// Section 3: Break-even ages
$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(59, 130, 246);
$pdf->Cell(0, 8, 'Break-Even Ages', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 10);
if (!empty($data['breakEvenAB'])) {
    $pdf->Cell(0, 6, 'A vs B: If you live past age ' . $data['breakEvenAB'] . ', claiming at ' . $b . ' gives more total benefits.', 0, 1);
}
if (!empty($data['breakEvenBC'])) {
    $pdf->Cell(0, 6, 'B vs C: If you live past age ' . $data['breakEvenBC'] . ', claiming at ' . $c . ' gives more total benefits.', 0, 1);
}
if (!empty($data['breakEvenAC'])) {
    $pdf->Cell(0, 6, 'A vs C: If you live past age ' . $data['breakEvenAC'] . ', claiming at ' . $c . ' gives more total benefits.', 0, 1);
}
$pdf->Ln(6);

// Section 4: Recommendation
$pdf->SetFont('helvetica', 'B', 14);
$pdf->SetTextColor(59, 130, 246);
$pdf->Cell(0, 8, 'Recommendation (to age ' . $life . ')', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->SetFont('helvetica', '', 11);
$pdf->SetFillColor(236, 254, 255);
$pdf->Cell(0, 10, 'Best option: Claim at age ' . $bestAge . ' — Lifetime total: $' . number_format($best['total'] ?? 0, 0), 0, 1, 'L', true);
$pdf->Ln(8);

$pdf->SetFont('helvetica', 'I', 8);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(0, 5, 'Generated by RonBelisle.com. For planning only; verify with SSA and your advisor.', 0, 0, 'C');

$pdfBytes = $pdf->Output('', 'S');
ob_end_clean();
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="SS_Claiming_Summary_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . strlen($pdfBytes));
header('Cache-Control: private, max-age=0, must-revalidate');
echo $pdfBytes;
exit;
?>
