<?php
error_reporting(0);
ini_set('display_errors', 0);
ob_start(); // Prevent any stray output from corrupting the PDF
session_start();
require_once '../includes/db_config.php';
require_once '../vendor/autoload.php';

// Check if user is logged in and premium
if (!isset($_SESSION['user_id'])) {
    header('Content-Type: application/json');
    http_response_code(401);
    die(json_encode(['error' => 'Not logged in']));
}

$user_id = $_SESSION['user_id'];
$stmt = $conn->prepare("SELECT subscription_status FROM users WHERE id = ?");
$stmt->bind_param("i", $user_id);
$stmt->execute();
$result = $stmt->get_result();
$user = $result->fetch_assoc();

if ($user['subscription_status'] !== 'premium') {
    header('Content-Type: application/json');
    http_response_code(403);
    die(json_encode(['error' => 'Premium subscription required']));
}

// Get POST data
$data = json_decode(file_get_contents('php://input'), true);

if (!$data) {
    header('Content-Type: application/json');
    http_response_code(400);
    die(json_encode(['error' => 'No data provided']));
}

$required = ['currentAge', 'accountBalance', 'growthRate', 'projections'];
foreach ($required as $key) {
    if (!isset($data[$key]) || !is_array($data['projections'])) {
        header('Content-Type: application/json');
        http_response_code(400);
        die(json_encode(['error' => 'Missing required field: ' . $key]));
    }
}

// Create PDF
$pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('RonBelisle.com');
$pdf->SetAuthor('RMD Impact Calculator');
$pdf->SetTitle('RMD Due Dates Calendar');
$pdf->SetSubject('Retirement Planning');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(TRUE, 15);

// Add a page
$pdf->AddPage();

// Header with gradient background
$pdf->SetFillColor(138, 90, 213); // Purple color
$pdf->Rect(0, 0, 210, 35, 'F');

// Title
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('helvetica', 'B', 22);
$pdf->SetY(10);
$pdf->Cell(0, 10, 'Your RMD Due Dates', 0, 1, 'C');

// Subtitle
$pdf->SetFont('helvetica', '', 11);
$pdf->SetY(22);
$pdf->Cell(0, 6, 'Required Minimum Distribution Schedule', 0, 1, 'C');

// Reset text color
$pdf->SetTextColor(0, 0, 0);
$pdf->SetY(45);

// Current year
$currentYear = date('Y');
$currentAge = $data['currentAge'];
$rmdStartAge = 73;
$startYear = $currentYear + ($rmdStartAge - $currentAge);

// Info box
$pdf->SetFont('helvetica', '', 10);
$pdf->SetFillColor(240, 245, 255);
$pdf->SetDrawColor(138, 90, 213);
$pdf->SetLineWidth(0.3);
$pdf->Rect(15, $pdf->GetY(), 180, 12, 'DF');
$pdf->SetY($pdf->GetY() + 4);
$pdf->SetTextColor(50, 50, 50);
$pdf->Cell(0, 5, 'Your first RMD is due by December 31, ' . $startYear . ' (age ' . $rmdStartAge . ')', 0, 1, 'L');
$pdf->SetY($pdf->GetY() + 8);

// Table header
$pdf->SetFont('helvetica', 'B', 11);
$pdf->SetTextColor(138, 90, 213);
$pdf->Cell(0, 8, 'Year-by-Year Schedule', 0, 1);
$pdf->SetTextColor(0, 0, 0);
$pdf->Ln(3);

// Table
$pdf->SetFont('helvetica', '', 9);
$tableHtml = '<table border="1" cellpadding="6" style="border-collapse: collapse; width: 100%;">
<thead>
<tr style="background-color: #8a5ad5; color: white; font-weight: bold; text-align: center;">
<th width="20%">Year</th>
<th width="15%">Age</th>
<th width="30%">RMD Amount</th>
<th width="35%">Due Date</th>
</tr>
</thead>
<tbody>';

// Limit to 15 years or until age 100, whichever comes first
$maxYears = 15;
$count = 0;
foreach ($data['projections'] as $row) {
    if ($count >= $maxYears || $row['age'] > 100) {
        break;
    }
    
    $year = $startYear + $count;
    $dueDate = 'December 31, ' . $year;
    
    // Alternate row colors
    $rowColor = ($count % 2 == 0) ? '#f9fafb' : '#ffffff';
    
    $tableHtml .= '<tr style="background-color: ' . $rowColor . ';">
    <td style="text-align: center; font-weight: bold;">' . $year . '</td>
    <td style="text-align: center;">' . $row['age'] . '</td>
    <td style="text-align: right;">$' . number_format($row['rmdAmount'], 0) . '</td>
    <td style="text-align: center;">' . $dueDate . '</td>
    </tr>';
    
    $count++;
}

$tableHtml .= '</tbody></table>';

$pdf->writeHTML($tableHtml, true, false, true, false, '');

// Footer note
$pdf->SetY(-25);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->SetTextColor(120, 120, 120);
$pdf->Cell(0, 5, 'Generated by RonBelisle.com - Professional Financial Planning Tools', 0, 0, 'C');
$pdf->Ln(4);
$pdf->Cell(0, 5, 'This calendar is for planning purposes only. Always verify RMD requirements with your tax advisor.', 0, 0, 'C');

// Capture PDF to string so we can send it as the only output (no stray bytes)
$pdfBytes = $pdf->Output('', 'S');
ob_end_clean();
header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="RMD_Calendar_' . date('Y-m-d') . '.pdf"');
header('Content-Length: ' . strlen($pdfBytes));
header('Cache-Control: private, max-age=0, must-revalidate');
echo $pdfBytes;
exit;
?>
